experiment:
  name: "unetr_msd_liver"
  architecture: "unetr"
  dataset: "msd_liver"

data:
  dataset_root: "/content/drive/My Drive/datasets/MSD/Task03_Liver"
  batch_size: 1
  num_workers: 2
  cache_rate: 0.0
  patch_size: [96, 96, 96]

model:
  in_channels: 1
  out_channels: 3

training:
  max_epochs: 50
  learning_rate: 1e-4
  loss_function: "dice_ce"

paths:
  output_root: "/content/drive/My Drive/3d_medical_segmentation/results"
