experiment:
  name: "unetr_brats"
  architecture: "unetr"
  dataset: "brats"

data:
  dataset_root: "/content/drive/My Drive/datasets/BraTS/training_data1_v2"
  batch_size: 1
  num_workers: 2
  cache_rate: 0.0
  patch_size: [128, 128, 128]

model:
  in_channels: 4
  out_channels: 4

training:
  max_epochs: 50
  learning_rate: 1e-4
  loss_function: "dice_ce"

paths:
  output_root: "/content/drive/My Drive/3d_medical_segmentation/results"
